<?php

namespace Database\Seeders;

use App\Core\Enums\PricingModel;
use App\Core\Enums\ProductStatus;
use App\Core\Enums\PurchaseMode;
use App\Core\Enums\VisibilityStatus;
use App\Domains\Product\Services\ProductService;
use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $obsoleteCategorySlugs = [
            'cement-binders',
            'tiles-finishes',
            'ppe-site-safety',
            'aggregates',
            'e2e-hardware-fixings',
        ];

        $obsoleteProductSlugs = [
            'portland-cement-50kg',
            'ceramic-floor-tiles-60x60',
            'construction-safety-gloves',
            'washed-river-sand',
            'e2e-anchor-bolt-m12',
        ];

        Product::query()
            ->whereIn('slug', $obsoleteProductSlugs)
            ->get()
            ->each(function (Product $product): void {
                if (Schema::hasTable('cart_items')) {
                    DB::table('cart_items')->where('product_id', $product->id)->delete();
                }

                if (Schema::hasTable('quotation_request_product')) {
                    DB::table('quotation_request_product')->where('product_id', $product->id)->delete();
                }

                $product->delete();
            });

        ProductCategory::query()
            ->whereIn('slug', $obsoleteCategorySlugs)
            ->get()
            ->each(function (ProductCategory $category): void {
                $category->forceFill(['is_published' => false])->save();
                $category->delete();
            });

        $categories = [
            [
                'name' => 'Art & Studio',
                'slug' => 'art-studio',
                'description' => 'Drawing, painting, printmaking, and studio finishing supplies.',
                'sort_order' => 1,
                'image_key' => 'product_maries_water_colour_12',
            ],
        ];

        $categoryIds = [];
        foreach ($categories as $category) {
            $model = ProductCategory::query()->updateOrCreate(
                ['slug' => $category['slug']],
                [
                    ...$category,
                    'is_published' => true,
                ],
            );
            $categoryIds[$category['slug']] = $model->id;
        }

        $products = [
            [
                'title' => 'Lino Block Slab A4',
                'slug' => 'lino-block-slab-a4',
                'sku' => 'ART-LINO-A4',
                'category' => 'art-studio',
                'excerpt' => 'Blue linoleum block slab for printmaking — A4 size.',
                'body' => 'Carvable lino block for relief printing and studio work. Also available in A5, A3, and A1 on request.',
                'unit_of_measure' => 'piece',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 850,
                'price_unit' => 'piece',
                'stock_display' => 40,
                'is_featured' => true,
                'image_key' => 'product_lino_block_slab',
                'gallery_keys' => ['product_lino_block_slab_sizes'],
                'specifications' => ['Size' => 'A4', 'Material' => 'Linoleum'],
            ],
            [
                'title' => 'Essdee Assorted Lino Cutters 25',
                'slug' => 'essdee-lino-cutters-25',
                'sku' => 'ART-ESSDEE-25',
                'category' => 'art-studio',
                'excerpt' => 'Essdee 25 assorted lino cutter blades, styles 1–10.',
                'body' => 'Assorted cutter set for linoleum printmaking. Retail box notes handle not included; confirm kit contents on order.',
                'unit_of_measure' => 'set',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 2200,
                'price_unit' => 'set',
                'stock_display' => 25,
                'is_featured' => false,
                'image_key' => 'product_essdee_lino_cutters',
                'specifications' => ['Pieces' => '25', 'Styles' => '1–10', 'Brand' => 'Essdee'],
            ],
            [
                'title' => 'Printing Roller Brayer',
                'slug' => 'printing-roller-brayer',
                'sku' => 'ART-BRAYER',
                'category' => 'art-studio',
                'excerpt' => 'Handheld brayer for rolling ink onto lino and printing plates.',
                'body' => 'Red-handle printing roller with black rubber cylinder for even ink application in studio printmaking.',
                'unit_of_measure' => 'piece',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 1800,
                'price_unit' => 'piece',
                'stock_display' => 18,
                'is_featured' => false,
                'image_key' => 'product_printing_roller',
                'gallery_keys' => ['product_printing_roller_alt'],
                'specifications' => ['Type' => 'Brayer', 'Use' => 'Printmaking / ink rolling'],
            ],
            [
                'title' => 'Fevicryl Acrylic Emerald Green 200ml',
                'slug' => 'fevicryl-acrylic-emerald-200ml',
                'sku' => 'ART-FEV-AC16',
                'category' => 'art-studio',
                'excerpt' => 'Fevicryl acrylic colour tube — Phthalocyanine Emerald Green AC16, 200 ml.',
                'body' => 'Water-dilutable acrylic colour from Pidilite. Permanent when dry; suitable for multi-surface studio work.',
                'unit_of_measure' => 'tube',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 950,
                'price_unit' => 'tube',
                'stock_display' => 30,
                'is_featured' => false,
                'image_key' => 'product_fevicryl_acrylic_emerald',
                'specifications' => ['Volume' => '200 ml', 'Colour' => 'Emerald Green AC16', 'Brand' => 'Fevicryl'],
            ],
            [
                'title' => 'Marie\'s Oil Colour Set 12×12ml',
                'slug' => 'maries-oil-colour-12',
                'sku' => 'ART-MARIE-OIL-12',
                'category' => 'art-studio',
                'excerpt' => 'Marie\'s oil colour starter set — 12 tubes × 12 ml.',
                'body' => 'Classic oil colour assortment for studio and architectural model finishing. Conforms to ASTM D-4236 and EN71-3.',
                'unit_of_measure' => 'set',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 3200,
                'price_unit' => 'set',
                'stock_display' => 20,
                'is_featured' => true,
                'image_key' => 'product_maries_oil_colour_12',
                'specifications' => ['Tubes' => '12', 'Volume' => '12 ml each', 'Brand' => 'Marie\'s'],
            ],
            [
                'title' => 'Marie\'s Water Colour Set 12×12ml',
                'slug' => 'maries-water-colour-12',
                'sku' => 'ART-MARIE-WC-12',
                'category' => 'art-studio',
                'excerpt' => 'Marie\'s water colour set — 12 tubes × 12 ml in tray.',
                'body' => 'Student-to-studio watercolour assortment including titanium white, vermilion, ultramarine, viridian, and more.',
                'unit_of_measure' => 'set',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 2800,
                'price_unit' => 'set',
                'stock_display' => 22,
                'is_featured' => true,
                'image_key' => 'product_maries_water_colour_12',
                'gallery_keys' => ['product_maries_water_colour_12_box'],
                'specifications' => ['Tubes' => '12', 'Volume' => '12 ml each', 'Brand' => 'Marie\'s'],
            ],
            [
                'title' => 'ABRO Spray Paint Assorted',
                'slug' => 'abro-spray-paint-assorted',
                'sku' => 'ART-ABRO-SPRAY',
                'category' => 'art-studio',
                'excerpt' => 'ABRO all-purpose fast-dry spray paint for interior and exterior marking.',
                'body' => 'Aerosol spray paint suitable for site marking, metal, and general finishing. Colour options include red, blue, flat black, silver, green, and white.',
                'unit_of_measure' => 'can',
                'purchase_mode' => PurchaseMode::Both,
                'price_amount' => 650,
                'price_unit' => 'can',
                'stock_display' => 80,
                'is_featured' => true,
                'image_key' => 'product_abro_spray_paint',
                'specifications' => ['Brand' => 'ABRO', 'Use' => 'Interior / exterior', 'Dry' => 'Fast dry'],
            ],
            [
                'title' => 'Refined Linseed Oil 120ml',
                'slug' => 'refined-linseed-oil-120ml',
                'sku' => 'ART-LINSEED-120',
                'category' => 'art-studio',
                'excerpt' => 'Refined linseed oil medium for oil colour — 120 ml.',
                'body' => 'Artist oil colour medium from Zhengzhou Tianma. Also useful as a traditional wood finish additive.',
                'unit_of_measure' => 'bottle',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 750,
                'price_unit' => 'bottle',
                'stock_display' => 35,
                'is_featured' => false,
                'image_key' => 'product_refined_linseed_oil',
                'specifications' => ['Volume' => '120 ml', 'Type' => 'Oil colour medium'],
            ],
            [
                'title' => 'Crayola Coloured Pencils 12',
                'slug' => 'crayola-coloured-pencils-12',
                'sku' => 'ART-CRAYOLA-12',
                'category' => 'art-studio',
                'excerpt' => 'Crayola pre-sharpened coloured pencils — pack of 12.',
                'body' => 'Bright, long-lasting coloured pencils for drafting sketches, site notes, and studio colour work.',
                'unit_of_measure' => 'pack',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 650,
                'price_unit' => 'pack',
                'stock_display' => 60,
                'is_featured' => false,
                'image_key' => 'product_crayola_coloured_pencils_12',
                'specifications' => ['Count' => '12', 'Brand' => 'Crayola', 'Condition' => 'Pre-sharpened'],
            ],
            [
                'title' => 'Pelikan Coloured Pencils 12',
                'slug' => 'pelikan-coloured-pencils-12',
                'sku' => 'ART-PELIKAN-CP-12',
                'category' => 'art-studio',
                'excerpt' => 'Pelikan hexagonal coloured pencils — 12 colours, soft 3 mm lead.',
                'body' => 'Break-resistant soft leads with bright colour laydown. KEBS marked stock for local supply.',
                'unit_of_measure' => 'pack',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 780,
                'price_unit' => 'pack',
                'stock_display' => 55,
                'is_featured' => false,
                'image_key' => 'product_pelikan_coloured_pencils_12',
                'gallery_keys' => ['product_pelikan_coloured_pencils_12_back'],
                'specifications' => ['Count' => '12', 'Lead' => '3 mm soft', 'Brand' => 'Pelikan'],
            ],
            [
                'title' => 'Pelikan Willow Charcoal',
                'slug' => 'pelikan-willow-charcoal',
                'sku' => 'ART-PELIKAN-CHAR',
                'category' => 'art-studio',
                'excerpt' => 'Pelikan willow charcoal sticks burnt from willow wood.',
                'body' => 'Drawing charcoal approximately 3–5 mm diameter and 13–13.5 cm length. Ideal for sketching and layout studies.',
                'unit_of_measure' => 'box',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 900,
                'price_unit' => 'box',
                'stock_display' => 28,
                'is_featured' => false,
                'image_key' => 'product_pelikan_willow_charcoal',
                'specifications' => ['Diameter' => '3–5 mm', 'Length' => '13–13.5 cm', 'Brand' => 'Pelikan'],
            ],
            [
                'title' => 'Mont Marte Willow Charcoal 12pc',
                'slug' => 'mont-marte-willow-charcoal-12',
                'sku' => 'ART-MM-CHAR-12',
                'category' => 'art-studio',
                'excerpt' => 'Mont Marte Signature willow charcoal — 12 pieces (4 small / 4 medium / 4 large).',
                'body' => 'Assorted-diameter willow charcoal for sketching and value studies.',
                'unit_of_measure' => 'box',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 1100,
                'price_unit' => 'box',
                'stock_display' => 24,
                'is_featured' => false,
                'image_key' => 'product_mont_marte_willow_charcoal_12',
                'specifications' => ['Pieces' => '12', 'Sizes' => 'S/M/L ×4', 'Brand' => 'Mont Marte'],
            ],
            [
                'title' => 'Marie\'s Willow Charcoal 25pc',
                'slug' => 'maries-willow-charcoal-25',
                'sku' => 'ART-MARIE-CHAR-25',
                'category' => 'art-studio',
                'excerpt' => 'Marie\'s willow charcoal sticks — 25 piece tube.',
                'body' => 'Bulk tube of willow charcoal for studio sketching and site concept drawings.',
                'unit_of_measure' => 'tube',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 1400,
                'price_unit' => 'tube',
                'stock_display' => 20,
                'is_featured' => false,
                'image_key' => 'product_maries_willow_charcoal_25',
                'specifications' => ['Pieces' => '25', 'Brand' => 'Marie\'s'],
            ],
            [
                'title' => 'Chivalry White Charcoal Pencils 3',
                'slug' => 'chivalry-white-charcoal-3',
                'sku' => 'ART-CHIV-WCHAR-3',
                'category' => 'art-studio',
                'excerpt' => 'Chivalry white charcoal pencils — 3 piece medium pack.',
                'body' => 'White charcoal pencils for highlights on toned paper and mixed-media studies.',
                'unit_of_measure' => 'pack',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 680,
                'price_unit' => 'pack',
                'stock_display' => 30,
                'is_featured' => false,
                'image_key' => 'product_chivalry_white_charcoal_3',
                'specifications' => ['Count' => '3', 'Grade' => 'Medium', 'Brand' => 'Chivalry'],
            ],
            [
                'title' => 'Pentel Arts Oil Pastels 50',
                'slug' => 'pentel-oil-pastels-50',
                'sku' => 'ART-PENTEL-OP-50',
                'category' => 'art-studio',
                'excerpt' => 'Pentel Arts oil pastels — 50 fade-resistant colours (PHN-50U).',
                'body' => 'Brilliant, long-lasting oil pastels for colour studies and presentation boards.',
                'unit_of_measure' => 'set',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 4500,
                'price_unit' => 'set',
                'stock_display' => 15,
                'is_featured' => true,
                'image_key' => 'product_pentel_oil_pastels_50',
                'specifications' => ['Colours' => '50', 'Code' => 'PHN-50U', 'Brand' => 'Pentel Arts'],
            ],
            [
                'title' => 'Derwent Inktense Pencils 12 Tin',
                'slug' => 'derwent-inktense-12',
                'sku' => 'ART-DERWENT-INK-12',
                'category' => 'art-studio',
                'excerpt' => 'Derwent Inktense water-soluble ink pencils — 12 colour metal tin.',
                'body' => 'Professional Inktense pencils made in England. Permanent once dry; excellent for wash techniques and illustration.',
                'unit_of_measure' => 'tin',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 6200,
                'price_unit' => 'tin',
                'stock_display' => 12,
                'is_featured' => true,
                'image_key' => 'product_derwent_inktense_12',
                'specifications' => ['Count' => '12', 'Brand' => 'Derwent', 'Origin' => 'England'],
            ],
            [
                'title' => 'Detail Paintbrush Set 5',
                'slug' => 'detail-paintbrush-set-5',
                'sku' => 'ART-BRUSH-5',
                'category' => 'art-studio',
                'excerpt' => 'Five-piece fine-tip paintbrush set for detail work.',
                'body' => 'Synthetic orange-tip detail brushes with metal ferrules — four dark handles plus one longer purple handle.',
                'unit_of_measure' => 'set',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 950,
                'price_unit' => 'set',
                'stock_display' => 40,
                'is_featured' => false,
                'image_key' => 'product_detail_paintbrush_set_5',
                'specifications' => ['Pieces' => '5', 'Tip' => 'Fine pointed'],
            ],
            [
                'title' => 'Canson Montval Watercolour Paper',
                'slug' => 'canson-montval-paper',
                'sku' => 'ART-CANSON-MV',
                'category' => 'art-studio',
                'excerpt' => 'Canson Montval — 25 sheets, 185 g/m², 55×75 cm.',
                'body' => 'French-made watercolour paper pack (REF C200807101). Suitable for washes, presentation boards, and studio painting.',
                'unit_of_measure' => 'pack',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 7800,
                'price_unit' => 'pack',
                'stock_display' => 10,
                'is_featured' => true,
                'image_key' => 'product_canson_montval_paper',
                'specifications' => ['Sheets' => '25', 'Weight' => '185 g/m²', 'Size' => '55×75 cm', 'Brand' => 'Canson'],
            ],
            [
                'title' => 'Artline 999XF Gold Paint Marker',
                'slug' => 'artline-999xf-gold',
                'sku' => 'ART-ARTLINE-GOLD',
                'category' => 'art-studio',
                'excerpt' => 'Artline 999XF gold paint marker — 0.8 mm tip.',
                'body' => 'Permanent gold paint marker for metal, glass, plastic, and presentation labelling.',
                'unit_of_measure' => 'piece',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 550,
                'price_unit' => 'piece',
                'stock_display' => 45,
                'is_featured' => false,
                'image_key' => 'product_artline_999xf_gold',
                'specifications' => ['Tip' => '0.8 mm', 'Colour' => 'Gold', 'Brand' => 'Artline'],
            ],
            [
                'title' => 'Uni-ball Signo Silver UM-100',
                'slug' => 'uniball-signo-silver',
                'sku' => 'ART-UNI-SIGNO-AG',
                'category' => 'art-studio',
                'excerpt' => 'Uni-ball Signo UM-100 silver gel pen.',
                'body' => 'Metallic silver gel ink for annotations, signing, and drafting callouts.',
                'unit_of_measure' => 'piece',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 320,
                'price_unit' => 'piece',
                'stock_display' => 70,
                'is_featured' => false,
                'image_key' => 'product_uniball_signo_silver',
                'specifications' => ['Model' => 'UM-100(08)', 'Colour' => 'Silver', 'Brand' => 'Uni-ball'],
            ],
            [
                'title' => 'uni PX-20 Silver Paint Marker',
                'slug' => 'uni-px20-silver-marker',
                'sku' => 'ART-UNI-PX20',
                'category' => 'art-studio',
                'excerpt' => 'uni PX-20 silver paint marker — marks on most surfaces.',
                'body' => 'Industrial silver paint marker for site marking on metal, plastic, glass, and coated surfaces.',
                'unit_of_measure' => 'piece',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 680,
                'price_unit' => 'piece',
                'stock_display' => 50,
                'is_featured' => false,
                'image_key' => 'product_uni_px20_silver_marker',
                'specifications' => ['Model' => 'PX-20', 'Colour' => 'Silver', 'Brand' => 'uni'],
            ],
            [
                'title' => 'Dylon Dye Reindeer 22',
                'slug' => 'dylon-dye-reindeer-22',
                'sku' => 'ART-DYLON-22',
                'category' => 'art-studio',
                'excerpt' => 'Dylon multi-purpose fabric dye — Reindeer 22, 5 g sachet.',
                'body' => 'Hot-water multi-purpose textile dye for natural fabrics and studio textile treatments.',
                'unit_of_measure' => 'sachet',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 280,
                'price_unit' => 'sachet',
                'stock_display' => 80,
                'is_featured' => false,
                'image_key' => 'product_dylon_dye_reindeer',
                'specifications' => ['Colour' => 'Reindeer 22', 'Net' => '5 g', 'Brand' => 'Dylon'],
            ],
            [
                'title' => 'Dylon Dye Ebony Black 08',
                'slug' => 'dylon-dye-ebony-08',
                'sku' => 'ART-DYLON-08',
                'category' => 'art-studio',
                'excerpt' => 'Dylon multi-purpose fabric dye — Ebony 08 Black.',
                'body' => 'Deep black multi-purpose dye sachet for textile and fabric finishing work.',
                'unit_of_measure' => 'sachet',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 280,
                'price_unit' => 'sachet',
                'stock_display' => 80,
                'is_featured' => false,
                'image_key' => 'product_dylon_dye_ebony',
                'specifications' => ['Colour' => 'Ebony 08 Black', 'Brand' => 'Dylon'],
            ],
            [
                'title' => 'Brown Vat Dye Powder 25g',
                'slug' => 'brown-vat-dye-25g',
                'sku' => 'ART-VAT-BRN-25',
                'category' => 'art-studio',
                'excerpt' => 'Brown vat dye powder — 25 g jar for natural fabrics.',
                'body' => 'Water-based dyeing ink. Use with hydros and caustic to fix; hot water required. Works with natural fabrics and poly/cotton.',
                'unit_of_measure' => 'jar',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 450,
                'price_unit' => 'jar',
                'stock_display' => 35,
                'is_featured' => false,
                'image_key' => 'product_vat_dye_brown_25g',
                'specifications' => ['Net' => '25 g', 'Colour' => 'Brown', 'Fix' => 'Hydros & caustic'],
            ],
            [
                'title' => 'Glitter Art Shaker',
                'slug' => 'glitter-art-shaker',
                'sku' => 'ART-GLITTER-SHAKE',
                'category' => 'art-studio',
                'excerpt' => 'Multi-colour glitter art shaker tub for decorative finishes.',
                'body' => 'Clear shaker with segregated glitter colours for craft, model finishes, and decorative resin accents.',
                'unit_of_measure' => 'tub',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 520,
                'price_unit' => 'tub',
                'stock_display' => 40,
                'is_featured' => false,
                'image_key' => 'product_glitter_art_shaker',
                'specifications' => ['Type' => 'Shaker tub', 'Use' => 'Decorative / craft'],
            ],
            [
                'title' => 'Glitter Wheel 6 Colours',
                'slug' => 'glitter-wheel-6-colours',
                'sku' => 'ART-GLITTER-WHEEL',
                'category' => 'art-studio',
                'excerpt' => 'Six-compartment glitter wheel — red, blue, green, purple, gold, silver.',
                'body' => 'Assorted fine glitter set for epoxy accents, specialty coatings, and decorative finishes.',
                'unit_of_measure' => 'set',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 680,
                'price_unit' => 'set',
                'stock_display' => 32,
                'is_featured' => false,
                'image_key' => 'product_glitter_wheel_6colour',
                'gallery_keys' => ['product_glitter_wheel_6colour_alt'],
                'specifications' => ['Compartments' => '6', 'Colours' => 'RGB + purple/gold/silver'],
            ],
            [
                'title' => 'Specialist Crafts Marbling Ink 8×25ml',
                'slug' => 'specialist-crafts-marbling-ink',
                'sku' => 'ART-MARBLE-INK-8',
                'category' => 'art-studio',
                'excerpt' => 'Specialist Crafts marbling ink set — 8 × 25 ml (Made in England).',
                'body' => 'Use on a prepared marbling bath/ground for controlled decorative patterns. Code B256B set.',
                'unit_of_measure' => 'set',
                'purchase_mode' => PurchaseMode::Buy,
                'price_amount' => 5400,
                'price_unit' => 'set',
                'stock_display' => 8,
                'is_featured' => true,
                'image_key' => 'product_marbling_ink_set',
                'gallery_keys' => ['product_marbling_ink_set_alt'],
                'specifications' => ['Bottles' => '8 × 25 ml', 'Code' => 'B256B', 'Origin' => 'England'],
            ],
        ];

        foreach ($products as $index => $product) {
            $categorySlug = $product['category'];
            unset($product['category']);

            Product::query()->updateOrCreate(
                ['slug' => $product['slug']],
                [
                    ...$product,
                    'product_category_id' => $categoryIds[$categorySlug],
                    'status' => ProductStatus::Published,
                    'visibility' => VisibilityStatus::Public,
                    'pricing_model' => $product['pricing_model'] ?? PricingModel::Fixed,
                    'price_currency' => 'KES',
                    'taxable' => true,
                    'published_at' => now(),
                    'sort_order' => $index,
                    'icon_path' => 'M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5M10 11.25h4M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z',
                ],
            );
        }

        app(ProductService::class)->forget();
    }
}
