<?php

/**
 * Seed source for the public portfolio. Files stay in public/media/zyntech
 * and are referenced via config/zyntech-media.php image/video keys.
 */
return [
    [
        'title' => 'Commercial Courtyard — Stone & Paving',
        'slug' => 'commercial-courtyard',
        'category' => 'commercial',
        'type' => 'commercial',
        'meta' => 'Completed · Nairobi',
        'featured' => true,
        'image' => 'commercial_courtyard',
        'stage' => 'completed',
        'progress' => 100,
        'county' => 'Nairobi',
        'city' => 'Nairobi',
        'completion_year' => 2025,
    ],
    [
        'title' => 'Site Preparation — Ballast Delivery',
        'slug' => 'site-prep-ballast',
        'category' => 'site-preparation',
        'type' => 'commercial',
        'meta' => 'In progress · Nairobi',
        'featured' => false,
        'image' => 'site_prep_ballast',
        'stage' => 'site-preparation',
        'progress' => 45,
        'county' => 'Nairobi',
        'city' => 'Nairobi',
    ],
    [
        'title' => 'Hardscaping — Gravel Leveling',
        'slug' => 'paving-gravel-leveling',
        'category' => 'paving',
        'type' => 'landscaping',
        'meta' => 'In progress · Nairobi',
        'featured' => false,
        'image' => 'paving_gravel_leveling',
        'stage' => 'finishes',
        'progress' => 60,
        'county' => 'Nairobi',
        'city' => 'Nairobi',
    ],
    [
        'title' => 'Covered Walkway — Steel Frame',
        'slug' => 'structural-walkway',
        'category' => 'structural',
        'type' => 'structural',
        'meta' => 'In progress · Nairobi',
        'featured' => true,
        'image' => 'structural_walkway',
        'stage' => 'structure',
        'progress' => 70,
        'county' => 'Nairobi',
        'city' => 'Nairobi',
    ],
    [
        'title' => 'Courtyard House — Exterior Finish',
        'slug' => 'courtyard-house',
        'category' => 'residential',
        'type' => 'residential',
        'meta' => 'Completed · Nairobi',
        'featured' => false,
        'image' => 'commercial_courtyard',
        'stage' => 'completed',
        'progress' => 100,
        'county' => 'Nairobi',
        'city' => 'Nairobi',
        'completion_year' => 2024,
    ],
    [
        'title' => 'Garden Walkway — Pergola Structure',
        'slug' => 'garden-walkway',
        'category' => 'landscaping',
        'type' => 'landscaping',
        'meta' => 'Planning · Nairobi',
        'featured' => false,
        'image' => 'structural_walkway',
        'stage' => 'planning',
        'progress' => 10,
        'county' => 'Nairobi',
        'city' => 'Nairobi',
    ],
];
