<?php

/**
 * Seed source for the Knowledge Centre. Public images stay in public/media/zyntech
 * and are referenced via config/zyntech-media.php image keys.
 */
return [
    [
        'title' => 'Preparing a Kenyan residential site for construction',
        'slug' => 'preparing-residential-site',
        'category' => 'site-works',
        'type' => 'guide',
        'featured' => true,
        'image' => 'site_prep_ballast',
        'reading_level' => 'beginner',
        'reading_time' => 6,
        'services' => ['site-preparation', 'construction-management'],
        'projects' => ['site-prep-ballast'],
    ],
    [
        'title' => 'NCA and county building approvals in Kenya',
        'slug' => 'nca-county-approvals',
        'category' => 'regulations',
        'type' => 'regulation',
        'featured' => true,
        'image' => 'commercial_courtyard',
        'reading_level' => 'intermediate',
        'reading_time' => 8,
        'services' => ['plan-approvals', 'property-sketching'],
        'projects' => ['commercial-courtyard'],
    ],
    [
        'title' => 'Interlocking pavers vs natural stone for Nairobi courtyards',
        'slug' => 'pavers-vs-stone-courtyards',
        'category' => 'materials',
        'type' => 'material',
        'featured' => false,
        'image' => 'paving_gravel_leveling',
        'reading_level' => 'beginner',
        'reading_time' => 5,
        'services' => ['paving-hardscaping', 'exterior-design'],
        'projects' => ['paving-gravel-leveling', 'commercial-courtyard'],
    ],
    [
        'title' => 'Ballast delivery and compaction: what homeowners should know',
        'slug' => 'ballast-delivery-compaction',
        'category' => 'site-works',
        'type' => 'guide',
        'featured' => false,
        'image' => 'site_prep_ballast',
        'reading_level' => 'beginner',
        'reading_time' => 4,
        'services' => ['site-preparation'],
        'projects' => ['site-prep-ballast'],
    ],
    [
        'title' => 'Steel pergola frames for covered walkways',
        'slug' => 'steel-pergola-walkways',
        'category' => 'materials',
        'type' => 'guide',
        'featured' => false,
        'image' => 'structural_walkway',
        'reading_level' => 'intermediate',
        'reading_time' => 5,
        'services' => ['construction-management', 'exterior-design'],
        'projects' => ['structural-walkway', 'garden-walkway'],
    ],
    [
        'title' => 'BOQ basics: how plan estimation protects your budget',
        'slug' => 'boq-plan-estimation-budget',
        'category' => 'cost-planning',
        'type' => 'cost-guide',
        'featured' => true,
        'image' => 'commercial_courtyard',
        'reading_level' => 'beginner',
        'reading_time' => 7,
        'services' => ['plan-estimation', 'construction-management'],
        'projects' => ['courtyard-house'],
    ],
];
